name = "RelocatableFolders"
uuid = "05181044-ff0b-4ac5-8273-598c1e38db00"
authors = ["Michael Hatherly <michael@pumas.ai>"]
version = "1.0.1"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Scratch = "1.1"
julia = "1"

[extras]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JSON3", "Test"]
